"""Added created_at to comment

Revision ID: 160a673aae57
Revises: 9167e0b9de2d
Create Date: 2022-06-25 21:15:28.960003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160a673aae57'
down_revision = '9167e0b9de2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
